# Generated by Django 5.0.6 on 2024-06-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryi',
            fields=[
                ('bid', models.AutoField(max_length=14, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.IntegerField(choices=[(1, 'khrebat al-souq'), (2, 'yadoudeh'), (3, 'zezia'), (4, 'madaba')])),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.food')),
            ],
        ),
    ]
